name: Bow Workflow

on: workflow_dispatch

jobs:
  basic-workflow:
    name: Bow Workflow
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      
      - name: Print environment details
        run: env